//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Study.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Study.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remain seated and do not move around during the study, as otherwise the eye tracking data will become unusable. Your eye movements will only be recorded during the display of the codes.
        ///
        ///Next, the study will be explained in more detail..
        /// </summary>
        public static string CalibrationDone {
            get {
                return ResourceManager.GetString("CalibrationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please focus your gaze on the dot to calibrate your eye position.
        ///
        ///Next, a warm-up task will follow..
        /// </summary>
        public static string FixationInstructionsFocus {
            get {
                return ResourceManager.GetString("FixationInstructionsFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before each code snippet, you will see this dot:.
        /// </summary>
        public static string FixationInstructionsPoint {
            get {
                return ResourceManager.GetString("FixationInstructionsPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At the end of the study, you can provide your email address to be informed about the collected results of the study. The email address will not be stored together with the collected information of this session.
        ///
        ///If you have any further questions, please refer to the experimenter after the study.
        ///
        ///By clicking &apos;Continue&apos;, you confirm that you want to participate in this study..
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this study, you will be asked to review Java code snippets and determine their output, while your eye movements are recorded. Then you will rate the snippets and complete a brief questionnaire. The information collected during the study will be treated confidentially and cannot be linked to you.
        ///
        ///You are free to withdraw from the study at any time without giving any reasons, and all data collected up to that point will be deleted.
        ///
        ///Participation takes about 90 minutes..
        /// </summary>
        public static string InformedConsent {
            get {
                return ResourceManager.GetString("InformedConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The study consists of two sections: a quantitative and a qualitative part.
        ///
        ///In the quantitative part, you&apos;ll encounter 12 Java code snippets that compile and output to the console. Your objective is to comprehend each snippet and determine its resulting output. Please enter the correct output of each snippet on the subsequent slide. You&apos;ll have 5 minutes for each task. After 4 minutes, a reminder of the remaining time will be provided. Kindly aim for both efficiency and accuracy in your work.
        ///
        ///In the qu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Continue&apos; when you are ready for the next calibration..
        /// </summary>
        public static string InterCalibration {
            get {
                return ResourceManager.GetString("InterCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Continue&apos; when you are ready for the next snippet.
        /// </summary>
        public static string Intersnippet {
            get {
                return ResourceManager.GetString("Intersnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following questions have missing or invalid answers:.
        /// </summary>
        public static string QuestionErrorMessage {
            get {
                return ResourceManager.GetString("QuestionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in Questions.
        /// </summary>
        public static string QuestionErrorTitle {
            get {
                return ResourceManager.GetString("QuestionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please answer the following:.
        /// </summary>
        public static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What does the code output?.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide an answer.
        /// </summary>
        public static string ResultBoxEmptyMessage {
            get {
                return ResourceManager.GetString("ResultBoxEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Field Empty.
        /// </summary>
        public static string ResultBoxEmptyTitle {
            get {
                return ResourceManager.GetString("ResultBoxEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks complete. Thank you very much!
        ///
        ///Take a moment to rest before transitioning to the post-questionnaire phase.
        ///
        ///Kindly notify the supervisor of your progress..
        /// </summary>
        public static string SnippetsFinished {
            get {
                return ResourceManager.GetString("SnippetsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An eye tracker is used to record your eye movements.
        ///In order for it to track your gaze properly, it needs to be calibrated.
        ///
        ///To do this, please follow the instructions of the calibration program..
        /// </summary>
        public static string StartCalibrate {
            get {
                return ResourceManager.GetString("StartCalibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now the study starts.
        /// </summary>
        public static string StartTrials {
            get {
                return ResourceManager.GetString("StartTrials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your participation!.
        /// </summary>
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have 1 minute left.
        /// </summary>
        public static string TimeNearlyOutMessage {
            get {
                return ResourceManager.GetString("TimeNearlyOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Almost Up.
        /// </summary>
        public static string TimeNearlyOutTitle {
            get {
                return ResourceManager.GetString("TimeNearlyOutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time is up.
        /// </summary>
        public static string TimeOutMessage {
            get {
                return ResourceManager.GetString("TimeOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time&apos;s up.
        /// </summary>
        public static string TimeOutTitle {
            get {
                return ResourceManager.GetString("TimeOutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the study!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your answer:.
        /// </summary>
        public static string YourAnswer {
            get {
                return ResourceManager.GetString("YourAnswer", resourceCulture);
            }
        }
    }
}
